title: Keegans Blog
description: My Personal Blog
author: Keegan Harris
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/K1ish
about: Developer

baseurl: "http://b.k1i.me"
url: "http://b.k1i.me

disqus_shortname: K1ish
google_analytics: UA-72862926-1

share:
  twitter_username: K1ish
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
